### ISSUE TITLE
How to install Pebble?

### ISSUE THREAD

**Issue by stevenyap** [easafe/purescript-droplet#16]
The guide https://droplet.asafe.dev/migrations has no information on how to install Pebble.
Going to https://github.com/easafe/haskell-pebble also yields no information on it.

The migration tool seems to be not found on npm nor cabal.
May I know if I have missed out anything?
Where can I install Pebble?

**Comment by easafe** [comment]
Hello Steven,

https://github.com/easafe/purescript-droplet does mention it, ```npm i @easafe/pebble```, but you are correct, it is missing on the other places. Reason being: droplet uses a different scheme representation now, and I haven't found time yet to port the migration tool. So currently, even if you install pebble, it is no great help.
